import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";
import Link from "next/link";

export default function ChessGame() {
  // type boardProps = {
  //   colNum: number;
  // };
  // const Board = ({ colNum }: boardProps): JSX.Element => {
  //   const BoardRow = () => {
  //     return (
  //       <ol id="col-${props.colnum}">
  //         <li id="row-a">a</li>
  //         <li id="row-b">b</li>
  //         <li id="row-c">c</li>
  //         <li id="row-d">d</li>
  //         <li id="row-e">e</li>
  //         <li id="row-f">f</li>
  //         <li id="row-g">g</li>
  //         <li id="row-h">h</li>
  //       </ol>
  //     );
  //   };
  //   return (
  //     <div className="board-wrap">
  //       <BoardRow colNum={1} />
  //     </div>
  //   );
  // };
  return (
    <div className={styles.container}>
      <Head>
        <title>HARAHO - CHESS</title>
        <meta
          name="description"
          content="CHESS GAME Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h2 className={styles.h2}>
          <Link href="/">
            <span>HARAHO - CHESS</span>
          </Link>
        </h2>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <p>Let&apos;s CHESS !</p>
        </h1>
      </main>

      <footer className={styles.footer}>
        <p>Copyright&copy; 2022. HARAHO </p>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
